<?xml version="1.0"?>
<robot name="ridgeback" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- This file is a placeholder which is included by default from
       ridgeback.urdf.xacro. If a robot is being customized and requires
       additional URDF, set the RIDGEBACK_URDF_EXTRAS environment variable
       to the full path of the file you would like included. -->
    
    <xacro:property name="damping_coef" value="0.7" />
    <xacro:property name="friction_coef" value="0.5" />
    <xacro:property name="tow_hitch_mass" value="0.5" />
    <xacro:property name="cargo_cart_link_mass" value="2" />
    <xacro:property name="dead_weight" value="5" />
    <xacro:property name="wheel_holder_mass" value="0.1" />
    <xacro:property name="wheel_mass" value="0.5" />


    <joint name="tow_hitch_joint" type="fixed">
      <origin xyz="-0.319 0 0.280" rpy="0 0 0" />
      <parent link="top_link"/>
      <child link="tow_hitch_link" />
    </joint>

    <link name="tow_hitch_link">
      <visual>
        <origin xyz="0 0 0.0125" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.05" length="0.025"/>
        </geometry>
        <material name="yellow"/>
      </visual>
      <collision>
        <origin xyz="0 0 0.0125"/>
        <geometry>
          <cylinder radius="0.05" length="0.025"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tow_hitch_mass}"/>
        <inertia
          ixx="${((1/12)*tow_hitch_mass)*((3*0.05*0.05)+(0.025*0.025))}" ixy="0" ixz="0"
          iyy="${((1/12)*tow_hitch_mass)*((3*0.05*0.05)+(0.025*0.025))}" iyz="0"
          izz="${(0.5*tow_hitch_mass*0.05*0.05)}"/>
      </inertial>
    </link>


    <joint name="cargo_cart_joint" type="revolute">
      <origin xyz="0 0 0.025" rpy="0 0 0" />
      <parent link="tow_hitch_link"/>
      <child link="cargo_cart_link" />
      <axis xyz="0 0 1" />
      <limit lower="-${PI*0.5}" upper="${PI*0.5}" velocity="0" effort="0"/>
      <dynamics damping="${damping_coef}" friction="${friction_coef}" />
    </joint>

    <transmission name="cargo_cart_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="cargo_cart_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="cargo_cart_joint_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <link name="cargo_cart_link">
      <visual>
        <origin xyz="-0.2 0 0.0125" rpy="0 0 0" />
        <geometry>
          <box size="0.5 0.643 0.025"/>
          <material name="black"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="-0.2 0 0.0125"/>
        <geometry>
          <box size="0.5 0.643 0.025"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${cargo_cart_link_mass}"/>
        <inertia
          ixx="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.643*0.643)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.5*0.5)))}" iyz="0"
          izz="${(((1/12)*cargo_cart_link_mass)*((0.5*0.5) + (0.643*0.643)))}"/>
        </inertial>
    </link>


    <joint name="cargo_cart_mid_joint" type="fixed">
      <origin xyz="-0.4625 0 0.0125" rpy="0 0 0" />
      <parent link="cargo_cart_link"/>
      <child link="cargo_cart_mid_link" />
    </joint>

    <link name="cargo_cart_mid_link">
      <visual>
        <origin xyz="0 0 -0.0725" rpy="0 0 0" />
        <geometry>
          <box size="0.025 0.643 0.17"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.0725"/>
        <geometry>
          <box size="0.025 0.643 0.17"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${cargo_cart_link_mass}"/>
        <inertia
          ixx="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.643*0.643)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.17*0.17)))}" iyz="0"
          izz="${(((1/12)*cargo_cart_link_mass)*((0.17*0.17) + (0.643*0.643)))}"/>
      </inertial>
    </link>


    <joint name="cargo_cart_bed_joint" type="fixed">
      <origin xyz="0 0 -0.145" rpy="0 0 0" />
      <parent link="cargo_cart_mid_link"/>
      <child link="cargo_cart_bed_link" />
    </joint>

    <link name="cargo_cart_bed_link">
      <visual>
        <origin xyz="-0.2625 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.5 0.643 0.025"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="-0.2625 0 0"/>
        <geometry>
          <box size="0.5 0.643 0.025"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${cargo_cart_link_mass}"/>
        <inertia
          ixx="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.643*0.643)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.5*0.5)))}" iyz="0"
          izz="${(((1/12)*cargo_cart_link_mass)*((0.5*0.5) + (0.643*0.643)))}"/>
      </inertial>
    </link>


    <!-- <joint name="dead_weight_joint" type="fixed">
      <origin xyz="0 0 0.0125" rpy="0 0 0" />
      <parent link="cargo_cart_bed_link"/>
      <child link="dead_weight_link" />
    </joint>

    <link name="dead_weight_link">
      <visual>
        <origin xyz="-0.25 0 0.125" rpy="0 0 0" />
        <geometry>
          <box size="0.25 0.25 0.25"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="-0.25 0 0.125"/>
        <geometry>
          <box size="0.25 0.25 0.25"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${dead_weight}"/>
        <inertia
          ixx="${(((1/12)*dead_weight)*((0.25*0.25) + (0.25*0.25)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*dead_weight)*((0.25*0.25) + (0.25*0.25)))}" iyz="0"
          izz="${(((1/12)*dead_weight)*((0.25*0.25) + (0.25*0.25)))}"/>
      </inertial>
    </link> -->


    <xacro:macro name="wheel_holder" params="prefix side joint_type location s_location">

      <joint name="${prefix}_${side}_wheel_holder_joint" type="${joint_type}">
        <parent link="cargo_cart_bed_link"/>
        <child link="${prefix}_${side}_wheel_holder_link" />
        <origin xyz="${-(location+0.05)} ${s_location*0.28} -0.0125" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <!-- <limit lower="-${PI}" upper="${PI}" velocity="0" effort="0"/> -->
        <!-- <dynamics damping="${damping_coef}" friction="${friction_coef}" /> -->
      </joint>

      <!-- <transmission name="${prefix}_${side}_wheel_holder_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${prefix}_${side}_wheel_holder_joint">
          <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="${prefix}_${side}_wheel_holder_actuator">
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission> -->

      <link name="${prefix}_${side}_wheel_holder_link">
        <visual>
          <origin xyz="0 0 -0.005" rpy="0 0 0" />
          <geometry>
            <box size="0.05 0.0790 0.01"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 -0.005" rpy="0 0 0" />
          <geometry>
            <box size="0.05 0.0790 0.01"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${wheel_holder_mass}"/>
          <inertia
            ixx="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.0790*0.0790)))}" ixy="0" ixz="0"
            iyy="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.05*0.05)))}" iyz="0"
            izz="${(((1/12)*wheel_holder_mass)*((0.05*0.05) + (0.0790*0.0790)))}"/>
        </inertial>
      </link>


      <joint name="${prefix}_${side}_wheel_holder_mid_joint" type="fixed">
        <parent link="${prefix}_${side}_wheel_holder_link"/>
        <child link="${prefix}_${side}_wheel_holder_mid_link" />
        <origin xyz="0 ${s_location*0.0395} 0" rpy="0 0 0" />
      </joint>

      <link name="${prefix}_${side}_wheel_holder_mid_link">
        <visual>
          <origin xyz="0 ${s_location*0.005} -0.055" rpy="0 0 0" />
          <geometry>
            <box size="0.05 0.01 0.11"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 ${s_location*0.005} -0.055" rpy="0 0 0" />
          <geometry>
            <box size="0.05 0.01 0.11"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${wheel_holder_mass}"/>
          <inertia
            ixx="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.11*0.11)))}" ixy="0" ixz="0"
            iyy="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.05*0.05)))}" iyz="0"
            izz="${(((1/12)*wheel_holder_mass)*((0.11*0.11) + (0.05*0.05)))}"/>
        </inertial>
      </link>


      <joint name="${prefix}_${side}_cart_wheel_joint" type="continuous">
        <parent link="${prefix}_${side}_wheel_holder_mid_link"/>
        <child link="${prefix}_${side}_cart_wheel_link" />
        <axis xyz="0 1 0" />
        <origin xyz="0 ${-(s_location*wheel_width/2)} -0.11" rpy="0 0 0"/>
        <limit lower="-${PI*10000}" upper="${PI*10000}" velocity="0" effort="0"/>
      </joint>

      <transmission name="$${prefix}_${side}_cart_wheel_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${prefix}_${side}_cart_wheel_joint">
          <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="${prefix}_${side}_cart_wheel_actuator">
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>

      <link name="${prefix}_${side}_cart_wheel_link">
        <visual>
          <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
          <geometry>
            <mesh filename="package://ridgeback_description/meshes/wheel.stl"/>
          </geometry>
          <material name="black" />
        </visual>
        <collision>
          <origin xyz="0 0 0.000005" rpy="${PI/2} 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${wheel_mass}"/>
          <inertia
            ixx="${((1/12)*wheel_mass)*((3*0.0759*0.0759)+(0.0790*0.0790))}" ixy="0" ixz="0"
            iyy="${((1/12)*wheel_mass)*((3*0.0759*0.0759)+(0.0790*0.0790))}" iyz="0"
            izz="${(0.5*wheel_mass*0.0759*0.0759)}"/>
        </inertial>
      </link>

    </xacro:macro>

    <!-- <xacro:wheel_holder prefix="front" side="left" joint_type="fixed" location="0" s_location="1"> -->
    <!-- </xacro:wheel_holder> -->

    <!-- <xacro:wheel_holder prefix="front" side="right" joint_type="fixed" location="0" s_location="-1"> -->
    <!-- </xacro:wheel_holder> -->

    <xacro:wheel_holder prefix="rear" side="left" joint_type="fixed" location="0.4" s_location="1">
    </xacro:wheel_holder>

    <xacro:wheel_holder prefix="rear" side="right" joint_type="fixed" location="0.4" s_location="-1">
    </xacro:wheel_holder>

</robot>